### ISSUE TITLE
Allow for relationships

### ISSUE THREAD

**Issue by tigris** [mdub/config_mapper#8]
In a situation of nested components, it would be handy for child nodes to know about their parents.

```ruby
component_dict :teams do
  attribute :name

  component_dict :services do
    attribute :name

    def full_name
      "#{_parent.name} - #{service.name}"
    end
  end
end
```

At the moment, I think within the context of a `service` here, you don't have any access to the parent object. So something like this is not possible.

I'm not entire sure what options are available for implementing this, but happy to have a crack if you can give some guidance. Or just tell me it's a really bad idea 😄

**Comment by mdub** [comment]
I reckon there's a path for you to make it work. You can supply a `type` argument to `component_dict`, and it can be a Proc that returns a new instance. 

Let me know if you need more hints :-)

Not sure this needs/deserves to be a core feature of ConfigMapper.
